spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8080/realms/ecoswap/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/ecoswap}

server:
  port: ${SERVER_PORT:9000}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY:DEBUG}
